//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SessionType.
const (
	ClaudeCode       SessionType = "claude_code"
	MultiAgentShogun SessionType = "multi_agent_shogun"
)

// Valid indicates whether the value is a known member of the SessionType enum.
func (e SessionType) Valid() bool {
	switch e {
	case ClaudeCode:
		return true
	case MultiAgentShogun:
		return true
	default:
		return false
	}
}

// AllOutputsResponse defines model for AllOutputsResponse.
type AllOutputsResponse struct {
	// Panes Map of pane index (as string key) to output content
	Panes map[string]string `json:"panes"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	// Height tmux window height in rows
	Height *int `json:"height,omitempty"`

	// TmuxName Existing tmux session name to adopt (for claude_code type)
	TmuxName *string      `json:"tmux_name,omitempty"`
	Type     *SessionType `json:"type,omitempty"`

	// Width tmux window width in columns
	Width *int `json:"width,omitempty"`
}

// DiscoveredSession defines model for DiscoveredSession.
type DiscoveredSession struct {
	// TmuxNames Tmux session names (1 for claude_code, 2 for multi_agent_shogun)
	TmuxNames []string    `json:"tmux_names"`
	Type      SessionType `json:"type"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// OutputResponse defines model for OutputResponse.
type OutputResponse struct {
	Output string `json:"output"`
}

// ResizeRequest defines model for ResizeRequest.
type ResizeRequest struct {
	// ColWidths Per-column pane widths in cells. Only used for `multi_agent_shogun`
	// sessions and must contain exactly 3 entries corresponding to the
	// three columns of the 3x3 multiagent grid (left to right).
	ColWidths *[]int `json:"col_widths,omitempty"`

	// Height tmux window height in rows
	Height int `json:"height"`

	// RowHeights Per-row pane heights in cells. Only used for `multi_agent_shogun`
	// sessions and must contain exactly 3 entries corresponding to the
	// three rows of the 3x3 multiagent grid (top to bottom).
	RowHeights *[]int `json:"row_heights,omitempty"`

	// Width tmux window width in columns
	Width int `json:"width"`
}

// SendInputRequest defines model for SendInputRequest.
type SendInputRequest struct {
	// Keys Array of keys to send to the tmux session.
	// Each element is passed as a separate argument to `tmux send-keys`.
	// Plain text strings are sent as literal input.
	// Special key names (Enter, Escape, C-c, etc.) are interpreted by tmux.
	Keys []string `json:"keys"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`

	// PaneCount Number of panes (1 for claude_code, 10 for multi_agent_shogun)
	PaneCount int         `json:"pane_count"`
	TmuxName  string      `json:"tmux_name"`
	Type      SessionType `json:"type"`
}

// SessionType defines model for SessionType.
type SessionType string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// PaneIndex defines model for PaneIndex.
type PaneIndex = int

// SessionId defines model for SessionId.
type SessionId = string

// SendInputParams defines parameters for SendInput.
type SendInputParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// GetOutputParams defines parameters for GetOutput.
type GetOutputParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// SendInputJSONRequestBody defines body for SendInput for application/json ContentType.
type SendInputJSONRequestBody = SendInputRequest

// ResizeSessionJSONRequestBody defines body for ResizeSession for application/json ContentType.
type ResizeSessionJSONRequestBody = ResizeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all sessions
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Create a new session
	// (POST /sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Discover existing unmanaged tmux sessions
	// (GET /sessions/discover)
	DiscoverSessions(w http.ResponseWriter, r *http.Request)
	// Delete a session
	// (DELETE /sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Send input to a session
	// (POST /sessions/{sessionId}/input)
	SendInput(w http.ResponseWriter, r *http.Request, sessionId SessionId, params SendInputParams)
	// Get session output
	// (GET /sessions/{sessionId}/output)
	GetOutput(w http.ResponseWriter, r *http.Request, sessionId SessionId, params GetOutputParams)
	// Get all pane outputs
	// (GET /sessions/{sessionId}/outputs)
	GetAllOutputs(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Resize the tmux window
	// (POST /sessions/{sessionId}/resize)
	ResizeSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverSessions operation middleware
func (siw *ServerInterfaceWrapper) DiscoverSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendInput operation middleware
func (siw *ServerInterfaceWrapper) SendInput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SendInputParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendInput(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOutput operation middleware
func (siw *ServerInterfaceWrapper) GetOutput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOutputParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOutput(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllOutputs operation middleware
func (siw *ServerInterfaceWrapper) GetAllOutputs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllOutputs(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResizeSession operation middleware
func (siw *ServerInterfaceWrapper) ResizeSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResizeSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/discover", wrapper.DiscoverSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/sessions/{sessionId}", wrapper.DeleteSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/input", wrapper.SendInput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}/output", wrapper.GetOutput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}/outputs", wrapper.GetAllOutputs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/resize", wrapper.ResizeSession)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ33PbuBH+V3bQPkgN9MN20t5p5h4cxblqmvQ8UTzTmejGhsmVhDMJMABoS83of+8s",
	"QFKiSDlO4/P54d5IED8W3/ftYhf8wiKdZlqhcpaNvrBMGJGiQ+PfzoXCiYpxRS8x2sjIzEmt2Mh/Aknf",
	"wGlwwizQ9eGtNhAlIo/xMtIxgkVrpVaWg1bJGoYgLdyKRMb9maK+aZ44eSkWqNylXepFrqohIxjCT1A0",
	"ZkIhh6Pej/BTGOOH+GbbnynGmSSjPudo1owzJVJkI5ZV5nNmoyWmIuxjLvLEsdGQs1SsZJqnbPQjZ6lU",
	"4XnImVtnNIFUDhdo2GbD2TTYNYlpDr9aJtxyu5itvnNm8HMuDcZs5EyOu4sXE1tnpFqwDU0cPnq8T5Pk",
	"l9xlubMf0GZaWfScGJ2hcRILhlR4EHEsiQyRnNc67C3B94h7LzLQcw9dwV9HWAi94QbXXeJTeysg0sqh",
	"cqwCRF//hpHzeGz3+Kmw6ddGN87GBoXDArsP+DlH65p7WqJcLF2NnFfDfcNdmq/gTqpY30EYAFKB0XeW",
	"cYYrkWYJhnEVq8fD4Q6vRy3Ecj/tZeBwX+NnK2kdweKXLggG6ksYiVhnDjrzPcnTCt0tYlsaQsMX9leD",
	"czZifxlsPW9QaGBQAPWRum44u5OxW9Zg8Ts6jIsfQLBEOslTVUMmgFFC86oGzct2zTfofCNtpG/RYFxY",
	"2uSywtM2Af24j6OFzhHsIcjh2Dc1YwPBKh2m7TIvGoQxYv1/4b0naj+e7+6nTeBnxmjTRAHL5n2Hr68R",
	"urXNG+LA4TAQPPTrKxT92pb4gFb+Fw86ZaSTS6+nFiLP0fSCxEIgCf288DBJbB9+oXCfW4w9lVdNLq9m",
	"qoz0IFQMaW5DvBFSAa5E5JI1nAAqZyRaiLQxHovY+6MGt8SZckuDWGqdoppbIpysTnbPiIWRMXQSnDsa",
	"ZihudIsjo5TSAac4bo0XqVhNwsAT33f7si/A3aj2BIHM6LvLMN0Bwoy+C2wVvf4gumij93LldEZDrrVz",
	"Oj3IVR2SH76Pqp1A+0ShdddHw+qVYNp8dYoqnigfEQ646w2uW3g/pR0S2vSZULWo4oKQ2rHWn6kzES0B",
	"E0yJCmkhE5YUISwIsEiZoUMQZpH7Dk7DVTGBins0/VV/ps4TEoTDlStSCgvCUB6oHE2USIdGJCBpK/2Z",
	"mmYYSZGQdeV5cKYcGg5nNhIZchj3Ig7oon7XT0QQmsygwxiu134HQSAVF5/YEpNEM878TITmQ8+MPVo8",
	"ou1kHDj7Ip/txJfC8zPXJqUnFguHPSdTbEsLpE8oK/OZOLo+jk7il/hq/vfFP5Y/tI0hL76MdK5aosu/",
	"8/QaTZnitR+wR8N7TtjKlKOvpktbq8P0vYcY/73nsozLWXetqYHCd5m4h8GPhSmoyFM/sR2QGGdNeHbm",
	"2u5n6oTL70nYrf9eh0vfNJHZ22YxrGk9dZRqrluc/XwSuNbKGZ0kFHvHfkswptR0/G5SlVdwK4V3HzJE",
	"ukBi1HO5UpjA6fmEcXaLJuicDfsn/SFtVmeoRCbZiJ30h/0TD3uRIQzKqellgV6ahINwRdnE3knrpmUn",
	"2m2AzA84Hg5D0hEqDqpvsiyRkR89+M0Gd9sWUpVPP0BGLZ7eKIvINnKaahO+NMvTVJh1+Vkkyc53zjJt",
	"WxwwlDwUNBXeVeG1URqTQRyiWudanUHHrHXCOLtP4uHiOUxajKIQXxbV1JJnEOwEbUL1YgHLEqfcV4im",
	"dd5qRVxR3qJ1r3W8/ibO7qOqtVDcbIJX1HRy9GhrVvJoyqH4VPATE9uvvlGh960cqoaWdSd0ZilBOjO3",
	"aACLjrtaDFDV9eW7VB44iIs6bccVm3K3Nb2RXoQLgoDr3PnjVmkHUW4MKsrvUqHEAuP+TH1AlxtlC0H3",
	"/ga15DCIbrCT2JWazoQ0rRIrC8snDQ/NavYbAkUJsbhOsBYVno1Oyu1tnTxXBYV15vfE86W6ytoE4STo",
	"Wm5H/iWTxDbyyI7teg0YTPUtWpAO5kanhXYoc+w3yfcrbOPL7iXkp3aAtl0G24u5za/fqZp7g0X9mL8n",
	"ZgTAfMx4OXz5+2uhXJecda5zFe/rwNvjk/i2WLFD98Dn5T6FaT3aqAqxvpRwRt+gbSskfGJR1QSNskL5",
	"AVe+XgDvZI9QakjbqDCipTAiIoH0oVllHC4lZmqaZ5k21Gq346hYjpI8xhHsFSjTTETI4aO45vDav0Dn",
	"tYhuLD12+UxdZBze6DvF4R3OHYcPVORx+KdOkcOZijmciwVeZNA5X1xk3fBKA6jhjaIp3h713h4dc5iM",
	"oTNRFo3rcngzhk6gtuvtfq9jOZdoIDM4lyu0Ixj3oDN2JulyeN+DzmniBu/RiS6HaQ8606Wc+7uQs5CX",
	"2hHM2LgXzVgY9WLc5b5FVC2nvuV9b0Utp4l78Z+iy7R3kVW9/MQvLrJuW6SvKtnvcXT+1c7bXxchKjx+",
	"xtIoyTf1FN6ZHDd/aEDy1nnPCLHoSc4l/3sHCsDhmhB/LoGQGAtXD/7+/gHxcHvL2ppFjUXmcoPhFCzy",
	"pBAM/T1bsdvmgfczunC/+7Q+8DsJce+quoUY/7OwwPK5iOFn3KalpWlf0YF9oBDCvihJpIoxXMMUB19Z",
	"DrZJYvv377nmQC3/J1uQPy02DSVqz4ly0TDuIOnG/x85nA2F/yc7KXBxU0y8g8mV2qmrm4SH0Y+V9D7+",
	"8Vb/O/TszraS60BS/OcBt640tS9If43yvwAAAP//Nxhab+khAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
