//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for AuthStatusAuthMethod.
const (
	ApiKey   AuthStatusAuthMethod = "api_key"
	ClaudeAi AuthStatusAuthMethod = "claude.ai"
	None     AuthStatusAuthMethod = "none"
)

// Valid indicates whether the value is a known member of the AuthStatusAuthMethod enum.
func (e AuthStatusAuthMethod) Valid() bool {
	switch e {
	case ApiKey:
		return true
	case ClaudeAi:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for ConversationStatus.
const (
	ConversationStatusCompleted ConversationStatus = "completed"
	ConversationStatusIdle      ConversationStatus = "idle"
	ConversationStatusRunning   ConversationStatus = "running"
)

// Valid indicates whether the value is a known member of the ConversationStatus enum.
func (e ConversationStatus) Valid() bool {
	switch e {
	case ConversationStatusCompleted:
		return true
	case ConversationStatusIdle:
		return true
	case ConversationStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for ConversationDetailStatus.
const (
	ConversationDetailStatusCompleted ConversationDetailStatus = "completed"
	ConversationDetailStatusIdle      ConversationDetailStatus = "idle"
	ConversationDetailStatusRunning   ConversationDetailStatus = "running"
)

// Valid indicates whether the value is a known member of the ConversationDetailStatus enum.
func (e ConversationDetailStatus) Valid() bool {
	switch e {
	case ConversationDetailStatusCompleted:
		return true
	case ConversationDetailStatusIdle:
		return true
	case ConversationDetailStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for CreateConversationRequestExecutionMode.
const (
	CloudRunSandbox CreateConversationRequestExecutionMode = "cloud_run_sandbox"
	DockerGce       CreateConversationRequestExecutionMode = "docker_gce"
	Local           CreateConversationRequestExecutionMode = "local"
)

// Valid indicates whether the value is a known member of the CreateConversationRequestExecutionMode enum.
func (e CreateConversationRequestExecutionMode) Valid() bool {
	switch e {
	case CloudRunSandbox:
		return true
	case DockerGce:
		return true
	case Local:
		return true
	default:
		return false
	}
}

// Defines values for LoginRequestMethod.
const (
	Claudeai LoginRequestMethod = "claudeai"
	Console  LoginRequestMethod = "console"
)

// Valid indicates whether the value is a known member of the LoginRequestMethod enum.
func (e LoginRequestMethod) Valid() bool {
	switch e {
	case Claudeai:
		return true
	case Console:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for MessageStatus.
const (
	MessageStatusCompleted MessageStatus = "completed"
	MessageStatusError     MessageStatus = "error"
	MessageStatusStreaming MessageStatus = "streaming"
)

// Valid indicates whether the value is a known member of the MessageStatus enum.
func (e MessageStatus) Valid() bool {
	switch e {
	case MessageStatusCompleted:
		return true
	case MessageStatusError:
		return true
	case MessageStatusStreaming:
		return true
	default:
		return false
	}
}

// AppAuthError defines model for AppAuthError.
type AppAuthError struct {
	Message string `json:"message"`
}

// AppAuthLoginRequest defines model for AppAuthLoginRequest.
type AppAuthLoginRequest struct {
	Username string `json:"username"`
}

// AppAuthLoginResponse defines model for AppAuthLoginResponse.
type AppAuthLoginResponse struct {
	Token string  `json:"token"`
	User  AppUser `json:"user"`
}

// AppAuthMeResponse defines model for AppAuthMeResponse.
type AppAuthMeResponse struct {
	User AppUser `json:"user"`
}

// AppAuthUpdateMeRequest defines model for AppAuthUpdateMeRequest.
type AppAuthUpdateMeRequest struct {
	Nickname string `json:"nickname"`
}

// AppUser defines model for AppUser.
type AppUser struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// AuthCancelResponse defines model for AuthCancelResponse.
type AuthCancelResponse struct {
	Message string `json:"message"`
}

// AuthInputRequest defines model for AuthInputRequest.
type AuthInputRequest struct {
	// Input Input to send to the login process stdin (can be empty string for Enter)
	Input string `json:"input"`
}

// AuthInputResponse defines model for AuthInputResponse.
type AuthInputResponse struct {
	Message string `json:"message"`
}

// AuthOutputResponse defines model for AuthOutputResponse.
type AuthOutputResponse struct {
	// Cursor New cursor position for the next request
	Cursor int `json:"cursor"`

	// Data Base64-encoded PTY output bytes since the given cursor
	Data string `json:"data"`
}

// AuthStatus defines model for AuthStatus.
type AuthStatus struct {
	ApiKeySource     *string              `json:"apiKeySource,omitempty"`
	ApiProvider      *string              `json:"apiProvider,omitempty"`
	AuthMethod       AuthStatusAuthMethod `json:"authMethod"`
	Email            *string              `json:"email,omitempty"`
	LoggedIn         bool                 `json:"loggedIn"`
	LoginPending     bool                 `json:"loginPending"`
	LoginUrl         *string              `json:"loginUrl,omitempty"`
	OrgName          *string              `json:"orgName,omitempty"`
	SubscriptionType *string              `json:"subscriptionType,omitempty"`
}

// AuthStatusAuthMethod defines model for AuthStatus.AuthMethod.
type AuthStatusAuthMethod string

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Model     string             `json:"model"`

	// Status Execution status of the conversation
	Status       ConversationStatus `json:"status"`
	SystemPrompt *string            `json:"system_prompt,omitempty"`
	Title        string             `json:"title"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// ConversationStatus Execution status of the conversation
type ConversationStatus string

// ConversationDetail defines model for ConversationDetail.
type ConversationDetail struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Messages  []Message          `json:"messages"`
	Model     string             `json:"model"`

	// Status Execution status of the conversation
	Status       ConversationDetailStatus `json:"status"`
	SystemPrompt *string                  `json:"system_prompt,omitempty"`
	Title        string                   `json:"title"`
	UpdatedAt    time.Time                `json:"updated_at"`
}

// ConversationDetailStatus Execution status of the conversation
type ConversationDetailStatus string

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	// ExecutionMode 実行環境の選択（デフォルト: local）
	ExecutionMode *CreateConversationRequestExecutionMode `json:"execution_mode,omitempty"`
	Model         *string                                 `json:"model,omitempty"`
	SystemPrompt  *string                                 `json:"system_prompt,omitempty"`
	Title         *string                                 `json:"title,omitempty"`
}

// CreateConversationRequestExecutionMode 実行環境の選択（デフォルト: local）
type CreateConversationRequestExecutionMode string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Method *LoginRequestMethod `json:"method,omitempty"`
}

// LoginRequestMethod defines model for LoginRequest.Method.
type LoginRequestMethod string

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	LoggedIn *bool   `json:"loggedIn,omitempty"`
	LoginUrl *string `json:"loginUrl,omitempty"`
	Message  string  `json:"message"`
}

// Message defines model for Message.
type Message struct {
	ConversationId openapi_types.UUID      `json:"conversation_id"`
	CreatedAt      time.Time               `json:"created_at"`
	Id             openapi_types.UUID      `json:"id"`
	MessageData    *map[string]interface{} `json:"message_data,omitempty"`
	Role           MessageRole             `json:"role"`
	Status         *MessageStatus          `json:"status,omitempty"`
	UpdatedAt      *time.Time              `json:"updated_at,omitempty"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// MessageStatus defines model for Message.Status.
type MessageStatus string

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Content User message content
	Content string `json:"content"`
}

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	MessageId openapi_types.UUID `json:"message_id"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// ToolCallData defines model for ToolCallData.
type ToolCallData struct {
	InputJson string  `json:"input_json"`
	IsRunning *bool   `json:"is_running,omitempty"`
	Result    *string `json:"result,omitempty"`
	ToolName  string  `json:"tool_name"`
	ToolUseId string  `json:"tool_use_id"`
}

// ConversationId defines model for ConversationId.
type ConversationId = openapi_types.UUID

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// GetAuthOutputParams defines parameters for GetAuthOutput.
type GetAuthOutputParams struct {
	// Since Cursor position to start from (0 = all lines)
	Since *int `form:"since,omitempty" json:"since,omitempty"`
}

// AppAuthLoginJSONRequestBody defines body for AppAuthLogin for application/json ContentType.
type AppAuthLoginJSONRequestBody = AppAuthLoginRequest

// AppAuthUpdateMeJSONRequestBody defines body for AppAuthUpdateMe for application/json ContentType.
type AppAuthUpdateMeJSONRequestBody = AppAuthUpdateMeRequest

// SubmitAuthInputJSONRequestBody defines body for SubmitAuthInput for application/json ContentType.
type SubmitAuthInputJSONRequestBody = AuthInputRequest

// InitiateLoginJSONRequestBody defines body for InitiateLogin for application/json ContentType.
type InitiateLoginJSONRequestBody = LoginRequest

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with username
	// (POST /app-auth/login)
	AppAuthLogin(w http.ResponseWriter, r *http.Request)
	// Logout
	// (POST /app-auth/logout)
	AppAuthLogout(w http.ResponseWriter, r *http.Request)
	// Get current user info
	// (GET /app-auth/me)
	AppAuthGetMe(w http.ResponseWriter, r *http.Request)
	// Update current user info
	// (PATCH /app-auth/me)
	AppAuthUpdateMe(w http.ResponseWriter, r *http.Request)
	// Cancel the in-progress login PTY process
	// (POST /auth/cancel)
	CancelLogin(w http.ResponseWriter, r *http.Request)
	// Submit input to the login process stdin
	// (POST /auth/input)
	SubmitAuthInput(w http.ResponseWriter, r *http.Request)
	// Initiate login flow
	// (POST /auth/login)
	InitiateLogin(w http.ResponseWriter, r *http.Request)
	// Logout
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get buffered stdout from the login process
	// (GET /auth/output)
	GetAuthOutput(w http.ResponseWriter, r *http.Request, params GetAuthOutputParams)
	// Get authentication status
	// (GET /auth/status)
	GetAuthStatus(w http.ResponseWriter, r *http.Request)
	// List all conversations
	// (GET /conversations)
	ListConversations(w http.ResponseWriter, r *http.Request)
	// Create a new conversation
	// (POST /conversations)
	CreateConversation(w http.ResponseWriter, r *http.Request)
	// Delete a conversation
	// (DELETE /conversations/{conversationId})
	DeleteConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId)
	// Get conversation with message history
	// (GET /conversations/{conversationId})
	GetConversation(w http.ResponseWriter, r *http.Request, conversationId ConversationId)
	// Send a message and process the assistant response asynchronously
	// (POST /conversations/{conversationId}/messages)
	SendMessage(w http.ResponseWriter, r *http.Request, conversationId ConversationId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AppAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) AppAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) AppAuthLogout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppAuthGetMe operation middleware
func (siw *ServerInterfaceWrapper) AppAuthGetMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppAuthGetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppAuthUpdateMe operation middleware
func (siw *ServerInterfaceWrapper) AppAuthUpdateMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppAuthUpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelLogin operation middleware
func (siw *ServerInterfaceWrapper) CancelLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitAuthInput operation middleware
func (siw *ServerInterfaceWrapper) SubmitAuthInput(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitAuthInput(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InitiateLogin operation middleware
func (siw *ServerInterfaceWrapper) InitiateLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InitiateLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthOutput operation middleware
func (siw *ServerInterfaceWrapper) GetAuthOutput(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthOutputParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthOutput(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuthStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListConversations operation middleware
func (siw *ServerInterfaceWrapper) ListConversations(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListConversations(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateConversation operation middleware
func (siw *ServerInterfaceWrapper) CreateConversation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateConversation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteConversation operation middleware
func (siw *ServerInterfaceWrapper) DeleteConversation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", r.PathValue("conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteConversation(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", r.PathValue("conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConversation(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendMessage operation middleware
func (siw *ServerInterfaceWrapper) SendMessage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "conversationId" -------------
	var conversationId ConversationId

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", r.PathValue("conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "conversationId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendMessage(w, r, conversationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/app-auth/login", wrapper.AppAuthLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/app-auth/logout", wrapper.AppAuthLogout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/app-auth/me", wrapper.AppAuthGetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/app-auth/me", wrapper.AppAuthUpdateMe)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/cancel", wrapper.CancelLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/input", wrapper.SubmitAuthInput)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.InitiateLogin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/output", wrapper.GetAuthOutput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/status", wrapper.GetAuthStatus)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/conversations", wrapper.ListConversations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/conversations", wrapper.CreateConversation)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/conversations/{conversationId}", wrapper.DeleteConversation)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/conversations/{conversationId}", wrapper.GetConversation)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/conversations/{conversationId}/messages", wrapper.SendMessage)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaT28ctxX/KgTbQwKMtEqiBugCPciyYQi1HaGyDoFhLKiZt7uMZsgx+Sh7K+wh1aFp",
	"0VOBXlu0t6JA0GMP+TZC+ueUr1CQnJmdP+TuBt614ZPl4Ru+937vDx9/s7c0lUUpBQjUdHxLS6ZYAQjK",
	"/e9UihtQmiGX4iyzT7igY1oynNOEClYAHdO0K5RQBa8MV5DRMSoDCdXpHApm355KVTCkY2oMt5K4KO0O",
	"GhUXM7pcLmthp/2kLE8Mzh8pJZWzTckSFHJwqwVozWZg/+xv0zbhRSP4stEnr76CFOkyqVU8kTMufgWv",
	"DGgcajIalPd1k6pGcrMuXUqhYagM5TWIgKbEbW4XfqpgSsf0J6NV5EYVaqOTsry0Yn3D/K7VHmuMewpx",
	"y95G/ya9l2XGEKz2SAwET6+3i0EjGVF3WbnR3Z9nQcy3U+lyOa7T4PyUiRTyOLa7SWaD8zNRGoyiyO2q",
	"/SMDnSpe2pKlY+peIiiJBpHZf3EOJLd5SkolU9CaaMy4IB+lTJArIFCUuCDeRDKVijwSCOrjQEX3gHL6",
	"N9i+d4y+MLhWUWqU9h2nC9MzeE38Giml5vapc96iJeANElXh3ujlAmFmyyGhGUM23PIB0/D58QGIVGaQ",
	"kfPnXxLprCNXCwRNNBcpOAUzfgOiUr8RZ6csqR2J4XCBDI0e+s9K/ktYXEijUghWBSv5uZI3PPOVNFx3",
	"nQTn0hUVCFO4wpQCqHt5cg0La17OTAaHjLcsXG0CBeN5cPtczmaQnbW75JWUOTBRrXJxDiKz0nGJSxXe",
	"XKrZs3DRJ1SbqyZ4z93iplRsTO2A0jMyFJ/2yRvIUAUMIZsw7JyqtoceIC+ABvD0HW7DCZzQQmYQRkY3",
	"6dLN4UdvIDWuGLwEkVOXse25gCZNGvAst/YpI4TdOHEDSA4IWTAN9EIjFJNSyaLEoF3IMQ/Hy7hT5cfA",
	"FGrsfv8amQaHpB2Fjq5N8XwIWKU2y/MvpnT8Yv2h2smFZRLpi77BIxR60yH9tOqPy8ZOphRbxPqoDjj0",
	"0rrk3G8bFz13oE6RiQXRp9CUmdxGI5cps7B2k+r7b//y37/+4T9//Of3f7u7//rb/339r3///s8/fPfN",
	"/d1v7+/+dP+bv9/f/eP+7psxca//8N3vWhlW75jm0mQTZcREM5FdyTdWi0yvQU1mKQSzrcn+lX2+Sx1o",
	"KQTgwfHB5/TtsnS1czD9BpkTGX+hfrw+g71YKCPXz7zFoH17HBh3FSu0zEMILuOKYqftFt081qt3MhE8",
	"XW3Sa7KtzJ5s2T332Zi9nZN6kGBZ5kYQlp+3zPY3roGTSvrkq4Pp5vGEMq25RiZsA/MpHO7BTeev39eo",
	"gBX9/p0M0m3Xvbgfk8qzDvChIF+AyKpAR1M+lQJBBMZje2MgFfykltpkbi230ZoN4+52mRfOd/tuUL+L",
	"Z1x1K95vmA2ufft6o9bqtZDG51LmpyzPH1bJG7iWTL7SMnzx5XpSTwvBHqFAu4Z6S4XJc3Zl7e3UQasL",
	"S5lPRGy+c6tG15iv97Yt3N44abszxMKWE6RGcVxc2PPYI/AAmAJlh3KHv1uwTrrHK+DniKWnSbiYymGm",
	"npyRdM6QaNDaDmQFE2wGBQgkN5wR38LJ6ZOzZqwZ0zQ9QCME5OTk3D639eV3++Tw6PDIzcQlCFZyOqaf",
	"HR4dfkYTxwA5w0esLA/saDtyndrFVvrqshFumKMO+1FxRKDxgcwWvdpjZZnz1L04qlNixSBtIB8GZM6y",
	"GzabFj5jXOo7Fz49OtqTCVV9ORu6gXICRJvUXq6nJvd5YYqCqUWz/JrjnDSUkpXooC39VX4T3FZs4PHx",
	"MHe86MCmKlfdkNrO0hcvly97JltNXSt9nc0gbuBjwKdA9x+RFrEVCMepUcoWiTsWlwk9Pvpk1wb4MS6g",
	"+1JYqKTiv4bsx0H+GJCkLcuJawpLV53pPAp5zbXttwr7jN77KcT1Yfc2Zh9Y2L3Voci72rN1lzq6Md4d",
	"PB256sX7CsKQ+Yz2Qm9yXoPReOvfd4QCFwelkjMFWlfs5PnzL2uGsuV9w3KGnb8wVwXHhnDcVxn0ydh3",
	"XQADQjUAvSd+tQPEDvCuBn4eYD5lBbhnhF0IenHyqBJeU8kRCrkVpg0Dw5ngyBnCPieG/qiwz4BsORPw",
	"yu1+HdRwVKBOc/m6i+XacSA2B+w23ypCOexbaLgITw/WIc+CR6eHx4ArJt/No6vPli9uh6d7h7NHSTQy",
	"hWSqZEE+OiK/ICzPSc4F6I/d/E7H9JUBtVh95HREPG1/y2x4nKMh3W8b9l6R7n3CCCB+gZlF3DlFmMiI",
	"aL5e9LC3Y8SVmU5BQWaL1L7mkBmUcCs+qyviuvhc1FTpe0o7uwoCq60rfjrgPovKjdqMQ9zfJ1zjaUfy",
	"LX3eisjtEcN9NndYhVwjkVPS9alXiVbGlkNPKImNEgMWeE+9Ok43Bxv37ia5LsqBy0NrnVQ8lMXrZztM",
	"8+gYeSbQ3g9zokHdgCJQCXZGKGcTYb4FdL3pZ/jotvtzjqVvdTkgDGP/0D3vxb7XikNerURGvV+Y7LVx",
	"9mivAJreoWoOOt5/9J5JJFNpRP+w93YQ1otWEm22H0wMAt/BNpWUo0Gab1HvOzTu0h0zj8y5RqkW2xTW",
	"qP3dLnJTWfHEuwnq7rtygFjf6qLz6X4siJd2JUJYmkJpL/1TOxL6uaaif4/fRcN+wLLmdyLvKpc75SQi",
	"iW1xJKzJZDsy1jc3Owg2n4pIHUnC9EKkcyWFNDp3A8fy/wEAAP//Eij00E8oAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
