[tools]
go = "1.26.1"
"golangci-lint" = "2.11.4"

[tasks."container-manager:dev:up"]
run = 'go run ./cmd/container-manager/ '

[tasks."container-manager:test"]
run = 'go test ./...'

[tasks."container-manager:lint"]
run = 'golangci-lint run ./...'

[tasks."container-manager:gen"]
description = "Regenerate the API code from api/openapi.yaml"
run = '''
cd api && \
go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.4.1 -config oapi-codegen.yaml openapi.yaml
'''
