import createClient from 'openapi-fetch';
import type { paths, components } from './schema';

export type SessionType = components['schemas']['SessionType'];
export type Session = components['schemas']['Session'];
export type DiscoveredSession = components['schemas']['DiscoveredSession'];
export type CreateSessionRequest = components['schemas']['CreateSessionRequest'];
export type OutputResponse = components['schemas']['OutputResponse'];
export type AllOutputsResponse = components['schemas']['AllOutputsResponse'];

/**
 * In production, BACKEND_URL is injected at runtime via window.__ENV__
 * (see /env.js, generated by Docker entrypoint).
 * In development, falls back to "" which lets Vite proxy handle it.
 */
const BACKEND_URL = window.__ENV__?.BACKEND_URL ?? '/api';

const client = createClient<paths>({ baseUrl: BACKEND_URL });

function throwOnError<T>(result: { data?: T; error?: unknown; response: Response }): T {
  if (result.error || !result.data) {
    throw new Error(`API error: ${result.response.status} ${result.response.statusText}`);
  }
  return result.data;
}

export async function createSession(opts?: Partial<CreateSessionRequest>): Promise<Session> {
  const result = await client.POST('/sessions', {
    body: opts as CreateSessionRequest,
  });
  return throwOnError(result);
}

export async function listSessions(): Promise<Session[]> {
  const result = await client.GET('/sessions');
  return throwOnError(result);
}

export async function discoverSessions(): Promise<DiscoveredSession[]> {
  const result = await client.GET('/sessions/discover');
  return throwOnError(result);
}

export async function sendKeys(id: string, keys: string[], paneIndex?: number): Promise<void> {
  const result = await client.POST('/sessions/{sessionId}/input', {
    params: {
      path: { sessionId: id },
      query: paneIndex != null ? { paneIndex } : undefined,
    },
    body: { keys },
  });
  throwOnError(result);
}

export async function resizeSession(id: string, width: number, height: number): Promise<void> {
  const result = await client.POST('/sessions/{sessionId}/resize', {
    params: { path: { sessionId: id } },
    body: { width, height },
  });
  throwOnError(result);
}

export async function getOutput(id: string, paneIndex?: number): Promise<string> {
  const result = await client.GET('/sessions/{sessionId}/output', {
    params: {
      path: { sessionId: id },
      query: paneIndex != null ? { paneIndex } : undefined,
    },
  });
  return throwOnError(result).output;
}

export async function getAllOutputs(id: string): Promise<Record<string, string>> {
  const result = await client.GET('/sessions/{sessionId}/outputs', {
    params: { path: { sessionId: id } },
  });
  return throwOnError(result).panes;
}

export async function deleteSession(id: string): Promise<void> {
  const result = await client.DELETE('/sessions/{sessionId}', {
    params: { path: { sessionId: id } },
  });
  throwOnError(result);
}
