/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all sessions */
        get: operations["listSessions"];
        put?: never;
        /**
         * Create a new session
         * @description Creates a new session. For claude_code type, creates a new tmux session and starts Claude Code CLI.
         *     For multi_agent_shogun type, starts the shogun startup script or adopts existing sessions.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discover existing unmanaged tmux sessions
         * @description Lists tmux sessions that exist but are not currently managed.
         *     Returns claude-* sessions and shogun/multiagent session pairs.
         */
        get: operations["discoverSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a session
         * @description Kills the tmux session(s) and removes it from management.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/resize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resize the tmux window
         * @description Resizes the tmux window of a running session.
         *
         *     For `multi_agent_shogun` sessions:
         *     - If `paneIndex` is not supplied (or omitted) the shogun and
         *       multiagent tmux sessions are both resized, and the optional
         *       `col_widths` / `row_heights` are applied to the multiagent grid.
         *     - If `paneIndex` is `0` only the shogun tmux session is resized.
         *     - If `paneIndex` is `1`–`9` only the multiagent tmux session is
         *       resized; `col_widths` / `row_heights` still apply.
         */
        post: operations["resizeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send input to a session
         * @description Sends keystrokes to the tmux session via send-keys.
         *     Each element in the `keys` array is passed as a separate argument to `tmux send-keys`.
         *     Plain text is sent as literal characters. Special key names are interpreted by tmux.
         *
         *     Supported special keys include: Enter, Escape, Space, Tab, BSpace (Backspace),
         *     Up, Down, Left, Right, Home, End, PageUp (PgUp), PageDown (PgDn),
         *     F1-F12, IC (Insert), DC (Delete).
         *
         *     Modifier prefixes: C- (Ctrl), M- (Alt/Meta), S- (Shift).
         *     Examples: "C-c" (Ctrl+C), "C-a" (Ctrl+A), "M-x" (Alt+X), "C-S-Up" (Ctrl+Shift+Up).
         */
        post: operations["sendInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get session output
         * @description Captures the current tmux pane content.
         */
        get: operations["getOutput"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all pane outputs
         * @description Captures the content of all panes in the session.
         */
        get: operations["getAllOutputs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SessionType: "claude_code" | "multi_agent_shogun";
        CreateSessionRequest: {
            /** @default claude_code */
            type: components["schemas"]["SessionType"];
            /** @description Existing tmux session name to adopt (for claude_code type) */
            tmux_name?: string;
            /**
             * @description tmux window width in columns
             * @default 200
             * @example 200
             */
            width: number;
            /**
             * @description tmux window height in rows
             * @default 50
             * @example 50
             */
            height: number;
        };
        Session: {
            /** @example a1b2c3d4e5f6g7h8 */
            id: string;
            type: components["schemas"]["SessionType"];
            /** @example claude-a1b2c3d4e5f6g7h8 */
            tmux_name: string;
            /**
             * @description Number of panes (1 for claude_code, 10 for multi_agent_shogun)
             * @example 1
             */
            pane_count: number;
            /** Format: date-time */
            created_at: string;
        };
        DiscoveredSession: {
            type: components["schemas"]["SessionType"];
            /** @description Tmux session names (1 for claude_code, 2 for multi_agent_shogun) */
            tmux_names: string[];
        };
        ResizeRequest: {
            /**
             * @description tmux window width in columns
             * @example 200
             */
            width: number;
            /**
             * @description tmux window height in rows
             * @example 50
             */
            height: number;
            /**
             * @description Per-column pane widths in cells. Only used for `multi_agent_shogun`
             *     sessions and must contain exactly 3 entries corresponding to the
             *     three columns of the 3x3 multiagent grid (left to right).
             */
            col_widths?: number[];
            /**
             * @description Per-row pane heights in cells. Only used for `multi_agent_shogun`
             *     sessions and must contain exactly 3 entries corresponding to the
             *     three rows of the 3x3 multiagent grid (top to bottom).
             */
            row_heights?: number[];
        };
        SendInputRequest: {
            /**
             * @description Array of keys to send to the tmux session.
             *     Each element is passed as a separate argument to `tmux send-keys`.
             *     Plain text strings are sent as literal input.
             *     Special key names (Enter, Escape, C-c, etc.) are interpreted by tmux.
             * @example [
             *       "hello",
             *       "Enter"
             *     ]
             */
            keys: string[];
        };
        OutputResponse: {
            output: string;
        };
        AllOutputsResponse: {
            /** @description Map of pane index (as string key) to output content */
            panes: {
                [key: string]: string;
            };
        };
        StatusResponse: {
            /** @example ok */
            status: string;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: {
        SessionId: string;
        /**
         * @description Pane index to target. For claude_code sessions, only 0 is valid.
         *     For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
         */
        PaneIndex: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    discoverSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of discoverable sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveredSession"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resizeSession: {
        parameters: {
            query?: {
                /**
                 * @description Pane index to target. For claude_code sessions, only 0 is valid.
                 *     For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
                 */
                paneIndex?: components["parameters"]["PaneIndex"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResizeRequest"];
            };
        };
        responses: {
            /** @description Session resized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sendInput: {
        parameters: {
            query?: {
                /**
                 * @description Pane index to target. For claude_code sessions, only 0 is valid.
                 *     For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
                 */
                paneIndex?: components["parameters"]["PaneIndex"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendInputRequest"];
            };
        };
        responses: {
            /** @description Input sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Invalid request body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOutput: {
        parameters: {
            query?: {
                /**
                 * @description Pane index to target. For claude_code sessions, only 0 is valid.
                 *     For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
                 */
                paneIndex?: components["parameters"]["PaneIndex"];
            };
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pane output */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputResponse"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAllOutputs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All pane outputs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllOutputsResponse"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
