//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// AgentInfo defines model for AgentInfo.
type AgentInfo struct {
	// Name Docker container name (matches the `name` from createAgent).
	Name string `json:"name"`
}

// CreateAgentRequest defines model for CreateAgentRequest.
type CreateAgentRequest struct {
	ContainerPort int32     `json:"container_port"`
	Env           *[]string `json:"env,omitempty"`

	// HostPort Optional published host port. 0 leaves it unpublished.
	HostPort *int32 `json:"host_port,omitempty"`
	Image    string `json:"image"`

	// Labels Docker container labels applied to the created container. The same
	// keys are forwarded to the `gcplogs` log driver via
	// `--log-opt labels=<csv>` and surface as Cloud Logging entry
	// labels.
	//
	// The server enforces an allowlist of keys: `conversation_id`,
	// `vm_instance_id`, `component`. Any other keys in the request are
	// silently dropped. Values longer than 256 bytes are truncated.
	// This bounds what reaches Cloud Logging since label values are not
	// redacted; callers should still avoid putting sensitive data here.
	Labels *map[string]string `json:"labels,omitempty"`

	// MemoryMib Memory limit in MiB; 0 means unlimited.
	MemoryMib *int64 `json:"memory_mib,omitempty"`
	Name      string `json:"name"`

	// NanoCpus CPU quota in 1e-9 CPUs; 0 means unlimited.
	NanoCpus *int64  `json:"nano_cpus,omitempty"`
	Network  *string `json:"network,omitempty"`
}

// CreateAgentResult defines model for CreateAgentResult.
type CreateAgentResult struct {
	Id string `json:"id"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status string `json:"status"`
}

// ListAgentsResult defines model for ListAgentsResult.
type ListAgentsResult struct {
	Agents []AgentInfo `json:"agents"`

	// Count Number of running cc-remote-agent containers on this VM.
	Count int32 `json:"count"`
}

// AgentName defines model for AgentName.
type AgentName = string

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe; also pings the Docker daemon.
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// List running cc-remote-agent containers on this VM.
	//
	// Filters containers by label `component=cc-remote-agent` so the count
	// reflects only agent containers, regardless of what other workloads
	// may run on the host. Intended for cc-tunnel's VM reaper to decide
	// whether a VM has been idle long enough to be deleted.
	// (GET /v1/agents)
	ListAgents(w http.ResponseWriter, r *http.Request)
	// Create and start an agent container.
	// (POST /v1/agents)
	CreateAgent(w http.ResponseWriter, r *http.Request)
	// Remove an agent container.
	// (DELETE /v1/agents/{name})
	RemoveAgent(w http.ResponseWriter, r *http.Request, name AgentName)
	// Stop a running agent container.
	// (POST /v1/agents/{name}/stop)
	StopAgent(w http.ResponseWriter, r *http.Request, name AgentName)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAgents operation middleware
func (siw *ServerInterfaceWrapper) ListAgents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAgents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAgent operation middleware
func (siw *ServerInterfaceWrapper) CreateAgent(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAgent(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveAgent operation middleware
func (siw *ServerInterfaceWrapper) RemoveAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name AgentName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveAgent(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopAgent operation middleware
func (siw *ServerInterfaceWrapper) StopAgent(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name AgentName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopAgent(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/agents", wrapper.ListAgents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agents", wrapper.CreateAgent)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/agents/{name}", wrapper.RemoveAgent)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/agents/{name}/stop", wrapper.StopAgent)

	return m
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthz503JSONResponse Error

func (response GetHealthz503JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgentsRequestObject struct {
}

type ListAgentsResponseObject interface {
	VisitListAgentsResponse(w http.ResponseWriter) error
}

type ListAgents200JSONResponse ListAgentsResult

func (response ListAgents200JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListAgents500JSONResponse Error

func (response ListAgents500JSONResponse) VisitListAgentsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgentRequestObject struct {
	Body *CreateAgentJSONRequestBody
}

type CreateAgentResponseObject interface {
	VisitCreateAgentResponse(w http.ResponseWriter) error
}

type CreateAgent201JSONResponse CreateAgentResult

func (response CreateAgent201JSONResponse) VisitCreateAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgent400JSONResponse Error

func (response CreateAgent400JSONResponse) VisitCreateAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateAgent500JSONResponse Error

func (response CreateAgent500JSONResponse) VisitCreateAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveAgentRequestObject struct {
	Name AgentName `json:"name"`
}

type RemoveAgentResponseObject interface {
	VisitRemoveAgentResponse(w http.ResponseWriter) error
}

type RemoveAgent204Response struct {
}

func (response RemoveAgent204Response) VisitRemoveAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveAgent404JSONResponse Error

func (response RemoveAgent404JSONResponse) VisitRemoveAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RemoveAgent500JSONResponse Error

func (response RemoveAgent500JSONResponse) VisitRemoveAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StopAgentRequestObject struct {
	Name AgentName `json:"name"`
}

type StopAgentResponseObject interface {
	VisitStopAgentResponse(w http.ResponseWriter) error
}

type StopAgent204Response struct {
}

func (response StopAgent204Response) VisitStopAgentResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type StopAgent404JSONResponse Error

func (response StopAgent404JSONResponse) VisitStopAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopAgent500JSONResponse Error

func (response StopAgent500JSONResponse) VisitStopAgentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe; also pings the Docker daemon.
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// List running cc-remote-agent containers on this VM.
	//
	// Filters containers by label `component=cc-remote-agent` so the count
	// reflects only agent containers, regardless of what other workloads
	// may run on the host. Intended for cc-tunnel's VM reaper to decide
	// whether a VM has been idle long enough to be deleted.
	// (GET /v1/agents)
	ListAgents(ctx context.Context, request ListAgentsRequestObject) (ListAgentsResponseObject, error)
	// Create and start an agent container.
	// (POST /v1/agents)
	CreateAgent(ctx context.Context, request CreateAgentRequestObject) (CreateAgentResponseObject, error)
	// Remove an agent container.
	// (DELETE /v1/agents/{name})
	RemoveAgent(ctx context.Context, request RemoveAgentRequestObject) (RemoveAgentResponseObject, error)
	// Stop a running agent container.
	// (POST /v1/agents/{name}/stop)
	StopAgent(ctx context.Context, request StopAgentRequestObject) (StopAgentResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListAgents operation middleware
func (sh *strictHandler) ListAgents(w http.ResponseWriter, r *http.Request) {
	var request ListAgentsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListAgents(ctx, request.(ListAgentsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListAgents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListAgentsResponseObject); ok {
		if err := validResponse.VisitListAgentsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateAgent operation middleware
func (sh *strictHandler) CreateAgent(w http.ResponseWriter, r *http.Request) {
	var request CreateAgentRequestObject

	var body CreateAgentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAgent(ctx, request.(CreateAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateAgentResponseObject); ok {
		if err := validResponse.VisitCreateAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveAgent operation middleware
func (sh *strictHandler) RemoveAgent(w http.ResponseWriter, r *http.Request, name AgentName) {
	var request RemoveAgentRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveAgent(ctx, request.(RemoveAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveAgentResponseObject); ok {
		if err := validResponse.VisitRemoveAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopAgent operation middleware
func (sh *strictHandler) StopAgent(w http.ResponseWriter, r *http.Request, name AgentName) {
	var request StopAgentRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopAgent(ctx, request.(StopAgentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopAgent")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopAgentResponseObject); ok {
		if err := validResponse.VisitStopAgentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYX2/TSBD/KiPfSQdS4qS0IJGKB+hxUKnlKjj6QlCz8U7spetZsztOyVX57qfddeKm",
	"NtDTAeLhnhKvZ2d+O39+M+vrJDNlZQiJXTK5TiphRYmMNjw9zZH4lSjRPyhKJkkluEgGCYW1+DNILH6s",
	"lUWZTNjWOEhcVmAp/B5eVV7OsVWUJ+v1evOyVX9MCxMsW1OhZYXhFTVGJbrMqoqV8dZ/N9klWsgMsVCE",
	"FrwY3CsFZwU64AJh5pdmsLCmhMyiYAxW7qfJoIPmJvJ30eT7rZSZf8CMk/UgOWrVvMaPNTru4t1CuqiM",
	"De8XxpaCk0miiPcftNYVMeZovWKkZXAsY+l6vLXdIqwVK/9cGMdbA7uu+TP8ERqqeq6VK1CClwYvncIY",
	"NIolOlAMNW1FvFPugFOVIsdegFrMUQfsQkoVEZztOKaz5SsRjRpBVJVWKIFNiGqMpGzlUvirQHCixCld",
	"4sqBsAgLY6+Ele22WZ5V2uRuBtrkIK1aooWlElOaDYfa5ENTcWPxybQej/ezzC3DH5yBIAmutguRIQgH",
	"R9rUEk5MnivKAYntakpxbzqlKQU8aL0FpIWxGToQBEJrc6WVYzAL8EgnMMsMLdE64X1woeRsMKXZsrxQ",
	"5FhQhmHJSzWFOUvhKa3AcIE2qABF4Xg2ZqM/+5Sc0kisVyCtqSqUKZwLXaMDbShHC1wIggcPH8F8xRj9",
	"xbamzPs19fCVg7mpSTq4KgSDRRGKavfcTlGG0WWwjPq9JjI8JYtSZIzyEDKhNVoHrjC1luBYaQ1iaZSE",
	"qmYOipCcYrVEkIIFFGgxnVLSU34llsauLko172b9aXgHWpWKvVdO1bNDGEOJghzUFNa7af7ooDfNN5zT",
	"SVkSZC6yqnZdAEdnb+FjbVh463s4fAxHZ2/df8CAfGXsZR937rJVrMnBhoJv8c9XaczVuofFlLyDYdmr",
	"/bm1xnY14mb5y0qjWJ/elyg0F29YcHT/rnq3XcdPoqx02Hv5VapvtvXZO1GOg4/c55wk8k2z3BL3rxYX",
	"yST5ZdQ201HT50Ztk+sh9MzU1EPmr+pyjtYzhq2JfLlk2dBiaRiHwXxLhA6MJwPl4Pz0TnR+yxURwWBz",
	"qq5L/AbV9OhdlFsMw1KQ8Bxjawp4PHXAi6PncH4aaFTF3mxIryDTyh/ALMKSNpnQU2ragBRYGoJ7b0l9",
	"AufX+H7qz841EWq4F8nodU33A8cEtQ4BSVZGEbspmWXgOoTzs6NDIAMWc+XYrnwPkUishHaQWeMiplZ5",
	"bADDSP8eeWBDYVcNLykO6dU5dTJIPJtHn4zTvXTsI2sqJFGpZJLsp+N0PxmE0Slky6gIOf23/59jCL/P",
	"r9AOjmUySV4gv2xEfLBcZcjF3HswHm+mDYyJExplFvaOPjiP4frG/PWlxNyprBDmW605BiP0ATHXmPpj",
	"PRzvfzMAkTL6LO9kQ003IfgJsi5LYVfJJDlRSyR0Dipr5ngIQjsDlaI8xnZHT9w7Wu6N2gLu9X7LAN/T",
	"+x2e6fHDSTM2bEjgduk3ERn/sIgEmu4GwfG/5Ck/L/2htL9m3JSYr5rJop19ntxSOAPXTISet/zMsdCY",
	"sYvcctvmwFe/sFL7HDGLONjEOcp3WW2EdFMqxcrjjwAxjM0pHHt3+lFyYWxLEr95+L4kKs8yBiRmSuKU",
	"rgoMWoV/XQgHc0QCJTWG8QuQTJ0XfsccQaLGOHT5+FXG9SThjWbdXLDQ8TMjV98s1j23mvVuc/CXuXWn",
	"BPa+D4LP1cDR9mbQ3AFC0h/8iKQ/pqXQSm7G7J+j2qLT4uWEheVwx9hN+9tMN7r2Q+I6NnCfet10e42l",
	"WW7T7eZHgHf9Z2hFRu1HgvX7TrYcdMeGaGsTx4Pv7842hcgwLHxX/zliGT1x9wiOHJsqDKS9nPGGTfVj",
	"QugtVf+HsPEEiM916LT55BU+C8RI1FYnk6RgriajUZh+fb+ZPB4/Hifr9+t/AgAA//97L4gAkBMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
