name: cc-tunnel-prepare
services:
  cc-remote-agent:
    build:
      context: ./cc-remote-agent
    image: cc-remote-agent:latest

  container-manager:
    build:
      context: ./container-manager
    image: container-manager:latest
