//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SessionType.
const (
	ClaudeCode       SessionType = "claude_code"
	MultiAgentShogun SessionType = "multi_agent_shogun"
)

// Valid indicates whether the value is a known member of the SessionType enum.
func (e SessionType) Valid() bool {
	switch e {
	case ClaudeCode:
		return true
	case MultiAgentShogun:
		return true
	default:
		return false
	}
}

// AllOutputsResponse defines model for AllOutputsResponse.
type AllOutputsResponse struct {
	// Panes Map of pane index (as string key) to output content
	Panes map[string]string `json:"panes"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	// Height tmux window height in rows
	Height *int `json:"height,omitempty"`

	// TmuxName Existing tmux session name to adopt (for claude_code type)
	TmuxName *string      `json:"tmux_name,omitempty"`
	Type     *SessionType `json:"type,omitempty"`

	// Width tmux window width in columns
	Width *int `json:"width,omitempty"`
}

// DiscoveredSession defines model for DiscoveredSession.
type DiscoveredSession struct {
	// TmuxNames Tmux session names (1 for claude_code, 2 for multi_agent_shogun)
	TmuxNames []string    `json:"tmux_names"`
	Type      SessionType `json:"type"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// OutputResponse defines model for OutputResponse.
type OutputResponse struct {
	Output string `json:"output"`
}

// ResizeRequest defines model for ResizeRequest.
type ResizeRequest struct {
	// ColWidths Per-column pane widths in cells. Only used for `multi_agent_shogun`
	// sessions and must contain exactly 3 entries corresponding to the
	// three columns of the 3x3 multiagent grid (left to right).
	ColWidths *[]int `json:"col_widths,omitempty"`

	// Height tmux window height in rows
	Height int `json:"height"`

	// RowHeights Per-row pane heights in cells. Only used for `multi_agent_shogun`
	// sessions and must contain exactly 3 entries corresponding to the
	// three rows of the 3x3 multiagent grid (top to bottom).
	RowHeights *[]int `json:"row_heights,omitempty"`

	// Width tmux window width in columns
	Width int `json:"width"`
}

// SendInputRequest defines model for SendInputRequest.
type SendInputRequest struct {
	// Keys Array of keys to send to the tmux session.
	// Each element is passed as a separate argument to `tmux send-keys`.
	// Plain text strings are sent as literal input.
	// Special key names (Enter, Escape, C-c, etc.) are interpreted by tmux.
	Keys []string `json:"keys"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`

	// PaneCount Number of panes (1 for claude_code, 10 for multi_agent_shogun)
	PaneCount int         `json:"pane_count"`
	TmuxName  string      `json:"tmux_name"`
	Type      SessionType `json:"type"`
}

// SessionType defines model for SessionType.
type SessionType string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// PaneIndex defines model for PaneIndex.
type PaneIndex = int

// SessionId defines model for SessionId.
type SessionId = string

// SendInputParams defines parameters for SendInput.
type SendInputParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// GetOutputParams defines parameters for GetOutput.
type GetOutputParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// SendInputJSONRequestBody defines body for SendInput for application/json ContentType.
type SendInputJSONRequestBody = SendInputRequest

// ResizeSessionJSONRequestBody defines body for ResizeSession for application/json ContentType.
type ResizeSessionJSONRequestBody = ResizeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all sessions
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Create a new session
	// (POST /sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Discover existing unmanaged tmux sessions
	// (GET /sessions/discover)
	DiscoverSessions(w http.ResponseWriter, r *http.Request)
	// Delete a session
	// (DELETE /sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Send input to a session
	// (POST /sessions/{sessionId}/input)
	SendInput(w http.ResponseWriter, r *http.Request, sessionId SessionId, params SendInputParams)
	// Get session output
	// (GET /sessions/{sessionId}/output)
	GetOutput(w http.ResponseWriter, r *http.Request, sessionId SessionId, params GetOutputParams)
	// Get all pane outputs
	// (GET /sessions/{sessionId}/outputs)
	GetAllOutputs(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Resize the tmux window
	// (POST /sessions/{sessionId}/resize)
	ResizeSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverSessions operation middleware
func (siw *ServerInterfaceWrapper) DiscoverSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendInput operation middleware
func (siw *ServerInterfaceWrapper) SendInput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SendInputParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendInput(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOutput operation middleware
func (siw *ServerInterfaceWrapper) GetOutput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOutputParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOutput(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllOutputs operation middleware
func (siw *ServerInterfaceWrapper) GetAllOutputs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllOutputs(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResizeSession operation middleware
func (siw *ServerInterfaceWrapper) ResizeSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResizeSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/discover", wrapper.DiscoverSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/sessions/{sessionId}", wrapper.DeleteSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/input", wrapper.SendInput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}/output", wrapper.GetOutput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}/outputs", wrapper.GetAllOutputs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/resize", wrapper.ResizeSession)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ33PbuBH+V3bQPkgN9MN20t5p5h4cxbl6mvQ8VjLTmejGgcmVhAsJMABoS83of+8s",
	"QFKkSDlO4/P54d4k/Fx837eLXfALi3SaaYXKWTb5wjJhRIoOjf93IRSeqxjX9CdGGxmZOakVm/gukNQH",
	"ToMTZoluCK+1gSgReYxXkY4RLFortbIctEo2MAZp4UYkMh7OFY1N88TJK7FE5a7sSi9zVU2ZwBh+gqIx",
	"Ewo5HA1+hJ/CHD/FN9vhXDHOJBn1OUezYZwpkSKbsKwynzMbrTAV4RwLkSeOTcacpWIt0zxlkx85S6UK",
	"v8ecuU1GC0jlcImGbbeczYJd5zGt4XfLhFvtNrNVP2cGP+fSYMwmzuRY37xY2Doj1ZJtaeHQ6fE+TZJf",
	"cpflzl6izbSy6DkxOkPjJBYMqfBDxLEkMkRy0RiwtwXfI+6tyEAvPHQFfz1hIYyGT7jpE5/aWwGRVg6V",
	"YxUg+vo3jJzHY3fGD4VNv7aGcTY1KBwW2F3i5xyta59phXK5cg1yXoz3DXdpvoZbqWJ9C2ECSAVG31rG",
	"Ga5FmiUY5lWsHo/HNV6POojlftmrwOG+xs/W0jqCxW9dEAw0ljASsc4c9BZ7kqcd+jvEdjSEhi/srwYX",
	"bML+Mtp53qjQwKgA6h0N3XJ2K2O3asDiT3QYFz+BYIl0kqeqgUwAo4TmRQOa592ab9H5StpI36DBuLC0",
	"zWWFp20D+m4fRwu9I9hDkMOxb2rHBoJVOky7ZV40CGPE5v/Ce0/Ufj6vn6dL4GfGaNNGAcvmfYdv7hGG",
	"da0b4sDhMBA89Os7FOO6trhEK/+LB50y0smV11MHkRdoBkFiIZCEcV54mCR2CL9QuM8txp7Kj20uP85V",
	"GelBqBjS3IZ4I6QCXIvIJRs4AVTOSLQQaWM8FrH3Rw1uhXPlVgax1DpFNbdCOFmf1O+IpZEx9BJcOJpm",
	"KG70iyujlNIBpzjujBepWJ+HiSd+7O7PvgDrUe0RApnRt1dhuQOEGX0b2CpG/UF00UHv5MrpjKZca+d0",
	"epCrJiQ/fB9VtUD7SKG17qNh90owXb46QxWfKx8RDrjrJ9x08H5KJyS0qZtQtajigpDGtTacqzMRrQAT",
	"TIkKaSETlhQhLAiwSJmhQxBmmfsBTsPHYgEVD2j5j8O5ukhIEA7XrkgpLAhDeaBytFAiHRqRgKSjDOdq",
	"lmEkRULWlffBmXJoOJzZSGTIYTqIOKCLhn2/EEFoMoMOY7je+BMEgVRcfGArTBLNOPMrEZr3vTP2aPGI",
	"dpNx4O6LfLYTXwnPz0KblH6xWDgcOJliV1ogfUJZmc/E0fVxdBI/xxeLvy//sfqhaw558VWkc9URXf6d",
	"p9doyhSv+4I9Gt9xw1amHH01XdpZHZYf3Mf4772XZVyuWremAQqvM3EHg+8KU1CRp35gNZAYZ214amvt",
	"zjNzwuV3JOzW9zfh0p/ayOwds5jWtp4GSrXQberPSfBKJHB6cR5I18oZnST7OawFrXwEmPoDw2WuFBrw",
	"RyXDpAukRgOaNXDUnUB9ecbZDZrgBWw8PB6OCQqdoRKZZBN2MhwPTzwpRf4wKremP0v0wiWUhCuKKvZG",
	"WjcrBxEWAVA/4Xg8DilJqEeo+smyREZ+9ug3G5xxV2ZVHn8PkXXEgVbRRLaRS1WH8IVbnqbCbMpukSS1",
	"fs4ybTvcMxREFFIV3lbBt1U4k0EcosbgRhVCl7B1wjhbkjiledM354dL67BoMYvoL0tuaskzCHaCNqG2",
	"sYBlAVSeK8TaJm+NEq8oftG6lzrefBNnd1HVWUZut8FnGjo5erA9K3m05VB0FfzExPaLb1ToXTuHmqJj",
	"38oDLZobNIDFwLoWA1RNffkhlQeO4qKKq7liW+52L2K4lXBBEHCdO38ZK+0gyo1BRdlfKpRYYjycq0t0",
	"uVG2EPTgb9BIHYPoRrW0r9R0JqTplFhZdj5qeGjXut8QKEqIxXWCjajwZHRSHm/n5LkqKGwyvyeeL9VD",
	"1zYIJ0HX8XbyL5kktpVl9mzfa8Bgqm/QgnSwMDottEN55bBNvt9hF1/qT5QfugHaDRntnu22v36nau4M",
	"Fs0k4I6YEQDzMeP5+Pnvr4VyX3LWhc5VvK8Db49P8btiRY3ukc/afYLTebVRjWJ9oeGM/oS2q8yAGyl2",
	"FUOr6AhZyUdfTYB3sgcoRKRt1R/RShgRkUCG0K5BDhcaczXLs0wbarW7eVRKR0ke4wT2ypdZJiLk8E5c",
	"c3jp/0DvpYg+WfrZ53P1PuPwSt8qDm9w4ThcUgnI4Z86RQ5nKuZwIZb4PoPexfJ91g9/aQI1vFK0xOuj",
	"weujYw7nU+idK4vG9Tm8mkIvUNv3dr/VsVxINJAZXMg12glMB9CbOpP0ObwdQO80caO36ESfw2wAvdlK",
	"LvxLyVnIWu0E5mw6iOYszHo27XPfIqqWU9/ydrCmltPEPftPMWQ2eJ9Vo/zCz95n/a5IX9W53+Po/KuD",
	"dx82QlR4+IylVbBvmwm+Mzlu/9CA5K3znhFi0aPcS/7jDxSAwzUh/lQCITEWHib86/494uHuDbYzi5qK",
	"zOUGwy1Y5EkhGPpXuOK07QvvZ3Th9fdxfeB3EuLeQ3YHMf5TYoHlUxHDz7hLS0vTvqIDe08hhHNRkkgV",
	"Y3ikKS6+shzsksTu2+BTzYE6vl52IH9aHBpK1J4S5aJl3EHSjf96cjgbCl9Xailw8Y5MvIPJlarV1W3C",
	"w+yHSnof/nprfjt6cndbyXUgKf7zgttUmtoXpH9G+V8AAAD//yWLS4oHIgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
