//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SessionType.
const (
	ClaudeCode       SessionType = "claude_code"
	MultiAgentShogun SessionType = "multi_agent_shogun"
)

// Valid indicates whether the value is a known member of the SessionType enum.
func (e SessionType) Valid() bool {
	switch e {
	case ClaudeCode:
		return true
	case MultiAgentShogun:
		return true
	default:
		return false
	}
}

// AllOutputsResponse defines model for AllOutputsResponse.
type AllOutputsResponse struct {
	// Panes Map of pane index (as string key) to output content
	Panes map[string]string `json:"panes"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	// Height tmux window height in rows
	Height *int `json:"height,omitempty"`

	// TmuxName Existing tmux session name to adopt (for claude_code type)
	TmuxName *string      `json:"tmux_name,omitempty"`
	Type     *SessionType `json:"type,omitempty"`

	// Width tmux window width in columns
	Width *int `json:"width,omitempty"`
}

// DiscoveredSession defines model for DiscoveredSession.
type DiscoveredSession struct {
	// TmuxNames Tmux session names (1 for claude_code, 2 for multi_agent_shogun)
	TmuxNames []string    `json:"tmux_names"`
	Type      SessionType `json:"type"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// OutputResponse defines model for OutputResponse.
type OutputResponse struct {
	Output string `json:"output"`
}

// ResizeRequest defines model for ResizeRequest.
type ResizeRequest struct {
	// Height tmux window height in rows
	Height int `json:"height"`

	// Width tmux window width in columns
	Width int `json:"width"`
}

// SendInputRequest defines model for SendInputRequest.
type SendInputRequest struct {
	// Keys Array of keys to send to the tmux session.
	// Each element is passed as a separate argument to `tmux send-keys`.
	// Plain text strings are sent as literal input.
	// Special key names (Enter, Escape, C-c, etc.) are interpreted by tmux.
	Keys []string `json:"keys"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`

	// PaneCount Number of panes (1 for claude_code, 10 for multi_agent_shogun)
	PaneCount int         `json:"pane_count"`
	TmuxName  string      `json:"tmux_name"`
	Type      SessionType `json:"type"`
}

// SessionType defines model for SessionType.
type SessionType string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// PaneIndex defines model for PaneIndex.
type PaneIndex = int

// SessionId defines model for SessionId.
type SessionId = string

// SendInputParams defines parameters for SendInput.
type SendInputParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// GetOutputParams defines parameters for GetOutput.
type GetOutputParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// SendInputJSONRequestBody defines body for SendInput for application/json ContentType.
type SendInputJSONRequestBody = SendInputRequest

// ResizeSessionJSONRequestBody defines body for ResizeSession for application/json ContentType.
type ResizeSessionJSONRequestBody = ResizeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all sessions
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Create a new session
	// (POST /sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Discover existing unmanaged tmux sessions
	// (GET /sessions/discover)
	DiscoverSessions(w http.ResponseWriter, r *http.Request)
	// Delete a session
	// (DELETE /sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Send input to a session
	// (POST /sessions/{sessionId}/input)
	SendInput(w http.ResponseWriter, r *http.Request, sessionId SessionId, params SendInputParams)
	// Get session output
	// (GET /sessions/{sessionId}/output)
	GetOutput(w http.ResponseWriter, r *http.Request, sessionId SessionId, params GetOutputParams)
	// Get all pane outputs
	// (GET /sessions/{sessionId}/outputs)
	GetAllOutputs(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Resize the tmux window
	// (POST /sessions/{sessionId}/resize)
	ResizeSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverSessions operation middleware
func (siw *ServerInterfaceWrapper) DiscoverSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendInput operation middleware
func (siw *ServerInterfaceWrapper) SendInput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SendInputParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendInput(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOutput operation middleware
func (siw *ServerInterfaceWrapper) GetOutput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOutputParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOutput(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllOutputs operation middleware
func (siw *ServerInterfaceWrapper) GetAllOutputs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllOutputs(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResizeSession operation middleware
func (siw *ServerInterfaceWrapper) ResizeSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResizeSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/discover", wrapper.DiscoverSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/sessions/{sessionId}", wrapper.DeleteSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/input", wrapper.SendInput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}/output", wrapper.GetOutput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}/outputs", wrapper.GetAllOutputs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/resize", wrapper.ResizeSession)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZW28buxH+KwO2D1JD3Zyk7RFwHhzFOTUat4YVAwWiA4feHUk83iU3JNe2Gui/F7zs",
	"fX1J4+P6oW9aXoff981whvpGIplmUqAwmsy/kYwplqJB5b5OmcBjEeOt/YhRR4pnhktB5q4LuO0DI8Ew",
	"tUEzhg9SQZSwPMaLSMYIGrXmUmgKUiQ7mALXcM0SHo9Xwo5N88TwC7ZBYS70Vm5yUU6ZwxR+htCYMYEU",
	"ZqOf4Gc/x01xzXq8EoQSbo36mqPaEUoES5HMSVaaT4mOtpgyf441yxND5lNKUnbL0zwl858oSbnwv6eU",
	"mF1mF+DC4AYV2e8pWXq7jmO7htstY2ZbbabLfkoUfs25wpjMjcqxvnlYWBvFxYbs7cK+0+F9mCT/zE2W",
	"G32GOpNCo+NEyQyV4RgYEv4Hi2NuyWDJaWNAawvaIu6EZSDXDrrA34Bp8KPhCndDy6d0VkAkhUFhSAmI",
	"vPwNI+PwqM74Odj0a2cYJQuFzGDA7gy/5qhN90xb5JutaZDzdto23KT5LdxwEcsb8BOAC1DyRhNK8Jal",
	"WYJ+XsnqwXRa43XWQyx1y154DtsaP7rl2lhY3NaBYLBjLUYslpmBwbolebvDsEKsosE3fCN/VLgmc/KH",
	"SeV5k6CBSQDqkx26p+SGx2bbgMWd6G5c3AQLSySTPBUNZDwYBTRvG9C86dd8h873XEfyGhXGwdIulyWe",
	"ugvopzaOGgYzaCFI4cA1dWODhZUbTPtlHhqYUmz3X+HdErWbT+vn6RP4kVJSdVHAornt8M09/LC+dX0c",
	"uDsMeA99eIcwrm+LM9T83/gop3wGP6xp/ZnUXYfJ706LQ/fBtUQRHwtHyh2IXeGuR/SHVpA25NpuGzg0",
	"ithdmltsRJbxShyxaAuYYGpvN64hY1pjDEwDA432cjYITG1yN8BI+BIWEPHILv9lvBKnCeMCDN6aENU1",
	"MGWvYmHsQgk3qFgC3B5lvBLLDCPOEmtd4ZJHwqCicKQjliGFxSiigCYaD91CFkKVKTQYw+XOncBfwSUX",
	"n8kWk0QSStxKFs3Hum2LFodoPxl3hJ/IXTjxBXP8rKVK7S8SM4Mjw1Psi8zc3eml+YTNLg+i1/EbfLv+",
	"8+Yv27/2zbFX3kUkc9HjIf/I00tUxS3bH+Nm03uCXGnK7MEbq7LaLz96jPE/Ghp5XKxat6YBCq0zcQ+D",
	"n4IpKKynfiY1kAglXXhqa1XnWRpm8ntyJu36m3DJqy4yrWOGaV3r7UAu1rJL/bEVvGAJHJ4ee9KlMEom",
	"STuN0CCFiwALd2A4y4VABe6o1jBuPKnRyM4aGdudQH15Qsk1Ku8FZDo+GE8tFDJDwTJO5uT1eDp+7Ugx",
	"W3f2SbG1/digE65FiZmQ15KPXJtlMchi4QF1Ew6mU+dfISW0CWiWJTxysye/ae+MVaZbevwjRNYTBzp5",
	"q7XNulR5CJc752nK1K7oZklS66ckk7rHPX1OakOqwJsy+HZqF2sQhagxuJEIMhGDNkwZXZC4sPMWH4/v",
	"rm78omGWpb+oemxLnoG3E6Ty6aUGLHLQ4lw+1jZ5a2TZof5Abd7JePddnN1HVW8mv997n2noZPZke5by",
	"6MohdAV+Ysv22+9U6H07+7SuZ9/SAzWqa1SAYWBdix6qpr7ckNIDJ3FIpGuu2JW7bkUMs2XGCwIuc+Mu",
	"YyENRLlSKEyyg5QJtkFbXJ+hyZXQQdCjP1WLONU60U1qlXSh6Yxx1SuxIvN/1vDQLTe+I1AUELPLBBtR",
	"4cXopDhe5eS5CBQ2mW+J51v51rD3wknQ9JSvf+dJojtZ5kAPnQYUpvIaNXADayXToB2bV4675LsdqvhS",
	"fyX63A9QNWRSvZzsf/1B1dwbLJpJwD0xwwPmYsab6ZvfXwvFvtZZ1zIXcVsHzh6X4vfFihrdE5e1uwSn",
	"92qzNYp2hYZR8gp1X5kB15xVFUOn6PBZyRdXTYBzsicoRLju1B/RlikWWYGMoVuD3F1orMQyzzKpbKuu",
	"5mngIkryGOfQKl+WGYuQwid2SeGd+4DBOxZdaftzSFfiPKPwXt4ICh9xbSic2RKQwt9kihSOREzhlG3w",
	"PIPB6eY8G/pPO8E2vBd2iQ+z0YfZAYXjBQyOhUZlhhTeL2DgqR06u09kzNccFWQK1/wW9RwWIxgsjEqG",
	"FE5GMDhMzOQEDRtSWI5gsNzytbFzj3zWquewIotRtCJ+1qvFkLoWVrYcupaT0a1tOUzMq3+FIcvReVaO",
	"cgu/Os+GfZG+rHN/xNHpg4Ort2UfFZ4+Y+kU7Ptmgm9Ujvv/aUBy1jnP8LHoWe4l9/4OAXC4tIi/lEBo",
	"GfMPE+6B9RHxsHoG682iFiwzuUJ/C4Y8yQdD9/4dTtu98H5B4x/gntcHfichtt4Se4hx/+YELF+KGH7B",
	"Ki0tTHtAB/qRQvDnskmirRj9I024+IpysE8S1d8zLzUH6vkDqQf5w3BoKFB7SZSzjnF3kq7cA/bd2ZB/",
	"4K6lwOEd2fIOKheiVld3Cfeznyrpffrrrfl8/+LutoJrT1L8/wtuV2qqLUj3jPKfAAAA///TGUh0ih8A",
	"AA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
