//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260404004943-9ea3cc79a4c7 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for SessionType.
const (
	ClaudeCode       SessionType = "claude_code"
	MultiAgentShogun SessionType = "multi_agent_shogun"
)

// Valid indicates whether the value is a known member of the SessionType enum.
func (e SessionType) Valid() bool {
	switch e {
	case ClaudeCode:
		return true
	case MultiAgentShogun:
		return true
	default:
		return false
	}
}

// AllOutputsResponse defines model for AllOutputsResponse.
type AllOutputsResponse struct {
	// Panes Map of pane index (as string key) to output content
	Panes map[string]string `json:"panes"`
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	// Height tmux window height in rows
	Height *int `json:"height,omitempty"`

	// TmuxName Existing tmux session name to adopt (for claude_code type)
	TmuxName *string      `json:"tmux_name,omitempty"`
	Type     *SessionType `json:"type,omitempty"`

	// Width tmux window width in columns
	Width *int `json:"width,omitempty"`
}

// DiscoveredSession defines model for DiscoveredSession.
type DiscoveredSession struct {
	// TmuxNames Tmux session names (1 for claude_code, 2 for multi_agent_shogun)
	TmuxNames []string    `json:"tmux_names"`
	Type      SessionType `json:"type"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// OutputResponse defines model for OutputResponse.
type OutputResponse struct {
	Output string `json:"output"`
}

// ResizeRequest defines model for ResizeRequest.
type ResizeRequest struct {
	// ColWidths Per-column pane widths in cells. Only used for `multi_agent_shogun`
	// sessions and must contain exactly 3 entries corresponding to the
	// three columns of the 3x3 multiagent grid (left to right).
	ColWidths *[]int `json:"col_widths,omitempty"`

	// Height tmux window height in rows
	Height int `json:"height"`

	// RowHeights Per-row pane heights in cells. Only used for `multi_agent_shogun`
	// sessions and must contain exactly 3 entries corresponding to the
	// three rows of the 3x3 multiagent grid (top to bottom).
	RowHeights *[]int `json:"row_heights,omitempty"`

	// Width tmux window width in columns
	Width int `json:"width"`
}

// SendInputRequest defines model for SendInputRequest.
type SendInputRequest struct {
	// Keys Array of keys to send to the tmux session.
	// Each element is passed as a separate argument to `tmux send-keys`.
	// Plain text strings are sent as literal input.
	// Special key names (Enter, Escape, C-c, etc.) are interpreted by tmux.
	Keys []string `json:"keys"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`

	// PaneCount Number of panes (1 for claude_code, 10 for multi_agent_shogun)
	PaneCount int         `json:"pane_count"`
	TmuxName  string      `json:"tmux_name"`
	Type      SessionType `json:"type"`
}

// SessionType defines model for SessionType.
type SessionType string

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// PaneIndex defines model for PaneIndex.
type PaneIndex = int

// SessionId defines model for SessionId.
type SessionId = string

// SendInputParams defines parameters for SendInput.
type SendInputParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// GetOutputParams defines parameters for GetOutput.
type GetOutputParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// ResizeSessionParams defines parameters for ResizeSession.
type ResizeSessionParams struct {
	// PaneIndex Pane index to target. For claude_code sessions, only 0 is valid.
	// For multi_agent_shogun sessions: 0 = shogun pane, 1-9 = multiagent panes.
	PaneIndex *PaneIndex `form:"paneIndex,omitempty" json:"paneIndex,omitempty"`
}

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// SendInputJSONRequestBody defines body for SendInput for application/json ContentType.
type SendInputJSONRequestBody = SendInputRequest

// ResizeSessionJSONRequestBody defines body for ResizeSession for application/json ContentType.
type ResizeSessionJSONRequestBody = ResizeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all sessions
	// (GET /sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Create a new session
	// (POST /sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)
	// Discover existing unmanaged tmux sessions
	// (GET /sessions/discover)
	DiscoverSessions(w http.ResponseWriter, r *http.Request)
	// Delete a session
	// (DELETE /sessions/{sessionId})
	DeleteSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Send input to a session
	// (POST /sessions/{sessionId}/input)
	SendInput(w http.ResponseWriter, r *http.Request, sessionId SessionId, params SendInputParams)
	// Get session output
	// (GET /sessions/{sessionId}/output)
	GetOutput(w http.ResponseWriter, r *http.Request, sessionId SessionId, params GetOutputParams)
	// Get all pane outputs
	// (GET /sessions/{sessionId}/outputs)
	GetAllOutputs(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Resize the tmux window
	// (POST /sessions/{sessionId}/resize)
	ResizeSession(w http.ResponseWriter, r *http.Request, sessionId SessionId, params ResizeSessionParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverSessions operation middleware
func (siw *ServerInterfaceWrapper) DiscoverSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendInput operation middleware
func (siw *ServerInterfaceWrapper) SendInput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SendInputParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendInput(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOutput operation middleware
func (siw *ServerInterfaceWrapper) GetOutput(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOutputParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOutput(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllOutputs operation middleware
func (siw *ServerInterfaceWrapper) GetAllOutputs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllOutputs(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResizeSession operation middleware
func (siw *ServerInterfaceWrapper) ResizeSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", r.PathValue("sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResizeSessionParams

	// ------------- Optional query parameter "paneIndex" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "paneIndex", r.URL.Query(), &params.PaneIndex, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "paneIndex", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResizeSession(w, r, sessionId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions", wrapper.ListSessions)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions", wrapper.CreateSession)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/discover", wrapper.DiscoverSessions)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/sessions/{sessionId}", wrapper.DeleteSession)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/input", wrapper.SendInput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}/output", wrapper.GetOutput)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/sessions/{sessionId}/outputs", wrapper.GetAllOutputs)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/sessions/{sessionId}/resize", wrapper.ResizeSession)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa23IbudF+lS78/wWZHR4k2ckuU3sh0/JGFTurkuyqVJlbIjTTJLGeAcYARiLjUlXe",
	"IW+YJ0k1gDlxhrIde726yJ2IARrd39fd6Ab0gcUqy5VEaQ2bfWA51zxDi9r9uuASz2WCW/qRoIm1yK1Q",
	"ks3cJxD0DawCy/Ua7RheKA1xyosEr2OVIBg0RihpIlAy3cEUhIFbnopkvJA0NytSK675GqW9Nhu1LmS1",
	"ZAZT+BHCYM4lRnA0+gF+9GvcEjdsxgvJIiZIqfcF6h2LmOQZshnLK/UjZuINZtzbseJFatlsGrGMb0VW",
	"ZGz2Q8QyIf3f04jZXU4ChLS4Rs3u7yN25fU6T0iG2y3ndlNvZqrvEdP4vhAaEzazusDm5kGwsVrINbsn",
	"wf6jw/s0TX8ubF5Yc4kmV9Kg40SrHLUVGBiS/g+eJILI4OlFa8LeFtEeca94DmrloAv8DbgBPxve4W5I",
	"fCqnBcRKWpSWVYCom18xtg6P2sa3QadfOtMiNtfILQbsLvF9gcZ2bdqgWG9si5yn033FbVZs4U7IRN2B",
	"XwBCglZ3hkUMtzzLU/TrKlaPp9MGr0c9xEZO7LXncN/Hz7bCWILFbR0IBppLGPFE5RYGqz2Xpx2GNWI1",
	"DX7gA/t/jSs2Y/83qSNvEnxgEoB6TVPvI3YnErtpweIsOoyLW0CwxCotMtlCxoNRQvO0Bc2Tfp/v0Plc",
	"mFjdosYkaNrlssLTdAF9vY+jgcER7CEYwbEb6uYGglVYzPrdPAxwrfnuv8J7z6nd+qhpT5+Dn2mtdBcF",
	"LIf3A769h5/WJ9fngcNpwEfox3cI8/q2uEQj/oEHgzJW6bXzpx4iL1CPvIv5ROLnOcfDNDVj+JnSfWEw",
	"cVQuu1wuF7LM9MBlAllhfL7hQgJueWzTHZwASqsFGoiV1g6LxMWjArvBhbQbjVj6OmU1u0E42Z40z4i1",
	"FgkMUlxZWqYpbwzDkVG60oGgOO7NFxnfnvuFJ25u/WPfAZtZ7RskMq3urr24A4RpdefZCrN+J7rI0Ae5",
	"siqnJTfKWpUd5KoNyfdfRlUj0X6j1NqMUb975TB9sXqFMjmXLiMcCNd3uOvh/ZQsJLTpM6FqUCaBkNax",
	"Nl7IMx5vAFPMiAphIOeGPIIb4GCQKkOLwPW6cBOsgmUQIJMRiV+OF/IiJYewuLWhpDDANdWB0pKgVFjU",
	"PAVBpowX8irHWPCUtCvPgzNpUUdwZmKeYwTzURwB2ng8dIIIQp1rtJjAzc5Z4B2k4uIt22CaKhYxJ4nQ",
	"/NQzY48Wh2g/GQfOvthVO8k1d/yslM7oL5ZwiyMrMuwrC4QrKCv1GT+6OY5Pkif4dPXH9Z823/etoSi+",
	"jlUhe7LL34rsBnVZ4vUfsEfTB07YSpWjj5ZLtdZe/OhTlP/Sc1kkpdSmNi1QoiYTDzD4OqiCkiL1LWuA",
	"xCLWhachq7bnynJbPFCwG/e9DZd610Vmz8ywrKs9TRRypbrUn5PDS57C6cW5J11Jq1Wa7tewBpR0GWDu",
	"DIbLQkrU4EwlxYT1pMYjWjWy9DmFpngWsVvUPgrYdHw8nhIUKkfJc8Fm7GQ8HZ84UkL9MCm3ph9rdI5L",
	"KHEbmir2Uhh7VU4iLDygbsHxdOpLEt+PUPeT56mI3erJr8YHY91mVRH/CU7Wkwc6TRPpRiFVGeEatyLL",
	"uN6Vn3maNr5HLFemJzx9Q0QpVeJdlXw7jTMpFEHcmtzqQugQNpZra0oS57Ru/vL8cGvthYZVRH/ZctNI",
	"kYPXE5T2vY0BLBug0i6fa9u8tVq80Pyisc9Usvsszh6iqreNvL/3MdPyk6OvtmflHl13CJ8CPwmx/fQz",
	"PfShnX1P0bNvFYEG9S1qwDCx6YseqrZ/uSlVBE6S0MU1QrHr7mYvY9gNt94h4Kaw7jCWykJcaI2Sqr+M",
	"S77GZLyQl2gLLU1w6NEfoFU6eqebNMq+0qdzLnSvi5Vt5zdND91e9zMSRQkxv0mxlRUejZ+U5tVBXshA",
	"YZv5Pef5UF103XvHSdH23J38VaSp6VSZAzN0PqAxU7doQFhYaZUF36G6ctwl3+1Q55fmFeXbfoDqKZP6",
	"2u7+ly/0mgeTRbsIeCBneMBczngyffLb+0K5LwXrShUy2fcDp48r8ftyRYPuiavaXYHTe7RRj2Jco2G1",
	"eoemr82AW8HrjqHTdPiqZOm6CXBB9hUaEWE6/Ue84ZrH5CBj6PYghxuNhbwq8lxpGjX1Omql47RIcAZ7",
	"7ctVzmOM4DW/ieCZ+wGDZzx+Z+jPYbSQb/IInqs7GcFLXNkILqkFjOAvKsMIzmQSwQVf45scBhfrN/nQ",
	"/6QFNPBckogXR6MXR8cRnM9hcC4NajuM4PkcBp7aodP7lUrESqCGXONKbNHMYD6CwdzqdBjBqxEMTlM7",
	"eYWWDyO4GsHgaiNW7qbkzFetZgYLNh/FC+ZXfTcfRm6EVyOnbuTVaEsjp6n97u9hytXoTV7NcoK/e5MP",
	"+zJ91ed+SaBHH51cP2z4rPD1K5ZOw37fLvCtLvD+d01ITjsXGT4XfZNzyT3+QAAcbgjxx5IIiTF/MeFu",
	"9z8hH9Z3sL1V1JznttDoT8FQJ/lk6G7hgrXdA+8ntP7299vGwG/kiHsX2T3EuKfEgOVjcYafsC5LS9U+",
	"4gfmEx3B20VFInWM/pImHHxlO9jnEvXb4GOtgXpeL3uQPw1GQ4naY6Kcd5Q7SLp2ryeHqyH/utIogcM9",
	"MvEOupCy0Ve7E/rFgZv3+kV8IUdwvoJl9a69pNqG7DEF4YUJDJQGlQlrMRk2W3wuk4WE5l17u7ujkudG",
	"2Q14s5LIlekkQOX+kZmWL+s3oSVMYNl4clg6ETyoESq/vav9cb8By+nS/3tAQ99WzShMqdYhCUfLf//z",
	"X8sfGnIOWArCkCFB3J8ftshYkabOpl1freIZ/gqNyWOoV9qPgY+uWCmDNxD3v4plVzngfoZx92L/CQAA",
	"//8aK+qq2CMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
